version: '4.14'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=bank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DB_SOURCE=postgres://root:secret@postgres:5432/bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ['/transactions/wait-for.sh', 'postgres:5432', '--', '/transactions/startup.sh']
    command: ['/transactions/main']